/** Minimal StockFlow server: holds OAuth secrets and proxies Google Sheets reads. */
import http from 'node:http';
import { readFile, stat, mkdir } from 'node:fs/promises';
import { createCipheriv, createDecipheriv, createHmac, createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { extname, join, normalize } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

function envFile(){return readFile('.env','utf8').then(s=>Object.fromEntries(s.split(/\r?\n/).filter(x=>x&&!x.trimStart().startsWith('#')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),x.slice(i+1).trim()]}))).catch(()=>({}))}
const config={...await envFile(),...process.env};
if(!config.SESSION_SECRET) console.warn('SESSION_SECRET is not set; using an ephemeral secret. Set it in .env before production.');
await mkdir(join(process.cwd(),'data'),{recursive:true});
const secret=config.SESSION_SECRET||randomBytes(32).toString('hex'), sessionKey=createHash('sha256').update(secret).digest(), database=new DatabaseSync(join(process.cwd(),'data','stockflow.db'));
database.exec(`CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, payload TEXT NOT NULL, expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS audit_events (id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS stock_actions (id TEXT PRIMARY KEY, status TEXT NOT NULL, payload TEXT NOT NULL, created_at INTEGER NOT NULL);`);
const sessions=new Map();
for(const row of database.prepare('SELECT id,payload,expires FROM sessions WHERE expires > ?').all(Date.now())) try { sessions.set(row.id,JSON.parse(row.payload)) } catch {}
const sign=id=>createHmac('sha256',secret).update(id).digest('base64url');
const seal=value=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',sessionKey,iv);const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${data.toString('base64url')}`};
const unseal=value=>{try{const [i,t,d]=value.split('.').map(x=>Buffer.from(x,'base64url')),dec=createDecipheriv('aes-256-gcm',sessionKey,i);dec.setAuthTag(t);return Buffer.concat([dec.update(d),dec.final()]).toString('utf8')}catch{return null}};
const persistSessions=async()=>{database.prepare('DELETE FROM sessions WHERE expires <= ?').run(Date.now());const upsert=database.prepare('INSERT OR REPLACE INTO sessions (id,payload,expires) VALUES (?,?,?)');for(const [id,s] of sessions)if(s.expires>Date.now())upsert.run(id,JSON.stringify({...s,token:s.token?seal(s.token):null,refreshToken:s.refreshToken?seal(s.refreshToken):null}),s.expires)};
for(const [id,s] of sessions){if(s.token)s.token=unseal(s.token);if(s.refreshToken)s.refreshToken=unseal(s.refreshToken);if(!s.token||s.expires<Date.now())sessions.delete(id)}
const redirect=config.GOOGLE_REDIRECT_URI||'http://localhost:8080/api/auth/callback';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
const staticFiles=new Set(['index.html','favicon.svg','public-placeholder.svg','src/app.js','src/calculations.js','src/storage.js','src/styles.css','src/improvements.css','src/responsive.css','src/shell-fix.css','src/brand-polish.css']);
const cookie=(req)=>Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=')));
const send=(res,status,data,headers={})=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff',...headers});res.end(JSON.stringify(data))};
function session(req,res){const [id,signature]=(cookie(req).stockflow||'.').split('.');let valid=id&&signature&&Buffer.from(signature).length===Buffer.from(sign(id)).length&&timingSafeEqual(Buffer.from(signature),Buffer.from(sign(id)));const secure=config.COOKIE_SECURE==='true'?'; Secure':'';if(!valid||!sessions.has(id)){const next=randomBytes(24).toString('hex'),value={expires:Date.now()+7*86400000,csrf:randomBytes(20).toString('base64url')};sessions.set(next,value);res.setHeader('Set-Cookie',`stockflow=${next}.${sign(next)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${secure}`);return value}const value=sessions.get(id);value.expires=Date.now()+7*86400000;void persistSessions();return value}
function requireWrite(req,s){const origin=req.headers.origin;if(origin&&origin!==new URL(redirect).origin)throw Error('Cross-site write request blocked.');if(req.headers['x-stockflow-csrf']!==s.csrf)throw Error('Invalid request token. Refresh and retry.')}
function requireConfig(){if(!config.GOOGLE_CLIENT_ID||!config.GOOGLE_CLIENT_SECRET)throw Error('Server OAuth configuration is missing. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env.');}
async function googleFetch(s,url,options={}){if(s.tokenExpires&&s.tokenExpires<Date.now()+30000&&s.refreshToken){const body=new URLSearchParams({client_id:config.GOOGLE_CLIENT_ID,client_secret:config.GOOGLE_CLIENT_SECRET,refresh_token:s.refreshToken,grant_type:'refresh_token'});const refresh=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!refresh.ok)throw Error('Google session expired. Sign in again.');const next=await refresh.json();s.token=next.access_token;s.tokenExpires=Date.now()+(next.expires_in||3600)*1000;await persistSessions()}return fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${s.token}`}})}
async function json(req){let body='';for await(const part of req){body+=part;if(body.length>1e6)throw Error('Request too large.')}return JSON.parse(body||'{}')}
const audit=async entry=>database.prepare('INSERT INTO audit_events (id,payload,created_at) VALUES (?,?,?)').run(entry.id,JSON.stringify(entry),Date.now());
const googleError=async r=>{try{return (await r.json()).error?.message}catch{return null}};
http.createServer(async(req,res)=>{try {const u=new URL(req.url,'http://localhost:8080');
 if(u.pathname==='/api/auth/start'){requireConfig();const s=session(req,res),nonce=randomBytes(20).toString('hex');s.nonce=nonce;await persistSessions();const p=new URLSearchParams({client_id:config.GOOGLE_CLIENT_ID,redirect_uri:redirect,response_type:'code',scope:'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive.metadata.readonly',access_type:'offline',prompt:'consent',state:nonce});res.writeHead(302,{Location:`https://accounts.google.com/o/oauth2/v2/auth?${p}`});return res.end()}
 if(u.pathname==='/api/auth/callback'){const s=session(req,res);if(u.searchParams.get('state')!==s.nonce)throw Error('Invalid OAuth state.');const body=new URLSearchParams({code:u.searchParams.get('code')||'',client_id:config.GOOGLE_CLIENT_ID,client_secret:config.GOOGLE_CLIENT_SECRET,redirect_uri:redirect,grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw Error('Google authorization token exchange failed.');const tokens=await r.json();s.token=tokens.access_token;s.refreshToken=tokens.refresh_token||s.refreshToken;s.tokenExpires=Date.now()+(tokens.expires_in||3600)*1000;await persistSessions();res.writeHead(302,{Location:'/?authorized=1'});return res.end()}
 if(u.pathname==='/health')return send(res,200,{ok:true});
 if(u.pathname==='/api/auth/status'){const s=session(req,res);return send(res,200,{authorized:Boolean(s.token),csrf:s.csrf})}
 if(u.pathname==='/api/files'){const s=session(req,res);if(!s.token)return send(res,401,{error:'Sign in with Google first.'});const q=new URLSearchParams({q:"mimeType='application/vnd.google-apps.spreadsheet' and trashed=false",pageSize:'100',orderBy:'modifiedTime desc',fields:'files(id,name,modifiedTime)'});const r=await googleFetch(s,`https://www.googleapis.com/drive/v3/files?${q}`);if(!r.ok)return send(res,r.status,{error:(await googleError(r))||'Could not list Google Sheets. Enable Google Drive API, then sign in again.'});return send(res,200,await r.json())}
 if(u.pathname==='/api/tabs'){const s=session(req,res),id=u.searchParams.get('id');if(!s.token)return send(res,401,{error:'Sign in with Google first.'});if(!id)return send(res,400,{error:'Spreadsheet ID is required.'});const r=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=sheets.properties`);if(!r.ok)return send(res,r.status,{error:'Could not read worksheet tabs.'});const body=await r.json();return send(res,200,{tabs:(body.sheets||[]).map(x=>x.properties.title)})}
 if(u.pathname==='/api/sheets'){const s=session(req,res);if(!s.token)return send(res,401,{error:'Sign in with Google first.'});const id=u.searchParams.get('id'),tab=u.searchParams.get('tab');if(!id||!tab)return send(res,400,{error:'Spreadsheet ID and worksheet tab are required.'});const r=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(tab)}?majorDimension=ROWS`);if(!r.ok)return send(res,r.status,{error:r.status===403?'Google denied access to this sheet.':r.status===404?'Spreadsheet or worksheet was not found.':'Google Sheets sync failed.'});return send(res,200,await r.json())}
 if(u.pathname==='/api/audit'){const s=session(req,res);if(!s.token)return send(res,401,{error:'Sign in with Google first.'});return send(res,200,{entries:database.prepare('SELECT payload FROM audit_events ORDER BY created_at DESC LIMIT 500').all().map(x=>JSON.parse(x.payload))})}
 if(u.pathname==='/api/stock/adjust'&&req.method==='POST'){const s=session(req,res);requireWrite(req,s);const body=await json(req),{id,tab,sku,expectedStock,delta,reason='Manual adjustment',actionId=randomBytes(16).toString('hex')}=body;if(!s.token)return send(res,401,{error:'Sign in with Google first.'});if(database.prepare('SELECT id FROM stock_actions WHERE id=?').get(actionId))return send(res,409,{error:'This stock action was already submitted.'});if(!id||!tab||!sku||!Number.isFinite(Number(delta)))return send(res,400,{error:'Sheet, tab, SKU and numeric adjustment are required.'});database.prepare('INSERT INTO stock_actions (id,status,payload,created_at) VALUES (?,?,?,?)').run(actionId,'pending',JSON.stringify(body),Date.now());const read=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(tab)}?majorDimension=ROWS`);if(!read.ok)return send(res,read.status,{error:'Could not read the current stock before updating.'});const values=(await read.json()).values||[],headers=values[0]||[],skuCol=headers.indexOf('Uniware SKU'),stockCol=headers.indexOf('STOCK');if(skuCol<0||stockCol<0)return send(res,400,{error:'Required Stock headers were not found.'});const matches=values.slice(1).map((r,i)=>({r,i})).filter(x=>String(x.r[skuCol]||'').trim().toUpperCase()===String(sku).trim().toUpperCase());if(matches.length!==1)return send(res,409,{error:matches.length?'Duplicate SKU: stock was not changed.':'SKU was not found.'});const current=Number(matches[0].r[stockCol]);if(!Number.isFinite(current)||current!==Number(expectedStock))return send(res,409,{error:'Stock changed in Google Sheets since this screen was loaded. Sync and review before retrying.'});const next=current+Number(delta);if(next<0)return send(res,400,{error:'This adjustment would make stock negative.'});const col=String.fromCharCode(65+stockCol),row=matches[0].i+2,range=`${tab}!${col}${row}`;const write=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[[next]]})});if(!write.ok)return send(res,write.status,{error:(await googleError(write))||'Google Sheets rejected the stock update.'});const entry={id:randomBytes(12).toString('hex'),actionId,at:new Date().toISOString(),sku,previous:current,next,delta:Number(delta),reason,sheet:id,tab,undone:false};database.prepare('UPDATE stock_actions SET status=?,payload=? WHERE id=?').run('completed',JSON.stringify(entry),actionId);await audit(entry);return send(res,200,{entry})}
 if(u.pathname==='/api/stock/undo'&&req.method==='POST'){const s=session(req,res);requireWrite(req,s);const body=await json(req),row=database.prepare('SELECT payload FROM audit_events WHERE id=?').get(body.id),entry=row&&JSON.parse(row.payload);if(!entry||entry.undone)return send(res,404,{error:'Undo entry was not found or has already been undone.'});const read=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(entry.sheet)}/values/${encodeURIComponent(entry.tab)}?majorDimension=ROWS`),values=(await read.json()).values||[],headers=values[0]||[],skuCol=headers.indexOf('Uniware SKU'),stockCol=headers.indexOf('STOCK'),match=values.slice(1).map((r,i)=>({r,i})).filter(x=>String(x.r[skuCol]||'').trim().toUpperCase()===String(entry.sku).trim().toUpperCase());if(!read.ok||match.length!==1)return send(res,409,{error:'Undo could not safely locate one current stock row.'});const current=Number(match[0].r[stockCol]);if(current!==entry.next)return send(res,409,{error:'Stock changed after this action. Undo is blocked to avoid overwriting a newer change.'});const col=String.fromCharCode(65+stockCol),range=`${entry.tab}!${col}${match[0].i+2}`,write=await googleFetch(s,`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(entry.sheet)}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[[entry.previous]]})});if(!write.ok)return send(res,502,{error:'Google Sheets rejected the undo.'});entry.undone=true;database.prepare('UPDATE audit_events SET payload=? WHERE id=?').run(JSON.stringify(entry),entry.id);return send(res,200,{entry})}
 const file=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)).replaceAll('\\','/');if(!staticFiles.has(file))return send(res,404,{error:'Not found.'});const path=normalize(join(process.cwd(),file));await stat(path);res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; img-src 'self' https: data:; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; base-uri 'self'; frame-ancestors 'none'"});res.end(await readFile(path));
}catch(e){console.error('Request failed:',e.message);send(res,500,{error:'The request could not be completed.'})}}).listen(8080,()=>console.log('StockFlow running at http://localhost:8080'));
