import {SALES_COLUMNS,STOCK_COLUMNS,normalizeSku,num,parseDate,aggregateSalesBySku,calculateDaysOfStock,dataQuality,suspiciousDuplicates} from './calculations.js';
import {load,save} from './storage.js';
const $=s=>document.querySelector(s), app=$('#app');
let csrf='';
let state={sales:[],stock:[],config:{sales:{url:'',tab:''},stock:{url:'',tab:''}},meta:{},page:'Dashboard',live:false,tablePage:1,detailSku:null,analyticsDim:'Sku',sidebarCollapsed:false};
const pages=['Dashboard','Inventory','Sales','Replenishment','Data Quality','Analytics','Settings'];
const today=new Date();
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v,n=0){return Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:n}):'—'}
function date(v){return v?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(v):'No Sales History'}
function extract(url){const m=String(url).match(/\/d\/([\w-]+)/)||String(url).match(/^([\w-]{20,})$/);return m?.[1]||null}
function rowsToObjects(values,columns){const headers=values[0]||[];const missing=columns.filter(x=>!headers.includes(x));if(missing.length)throw Error(`Missing required columns: ${missing.join(', ')}`);return values.slice(1).filter(r=>r.some(v=>String(v??'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function metrics(){return aggregateSalesBySku(state.sales,today)}
function inventory(){const m=metrics();return state.stock.map(r=>{const x=m.get(normalizeSku(r['Uniware SKU']))||{};const stock=num(r.STOCK);return {...r,_m:x,_stock:stock,_days:calculateDaysOfStock(stock,x.avgDaily)}})}
function exportCsv(rows,cols,name){const text=[cols,...rows.map(r=>cols.map(c=>JSON.stringify(r[c]??'')))].map(x=>x.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function header(){const icons=['▦','▤','↗','✓','◫','⌁','⚙'];return `<div class="stockflow-shell"><div class="workspace"><aside class="${state.sidebarCollapsed?'collapsed':''}"><div class="logo"><button id="brandToggle" title="Expand sidebar"><b>SF</b><span>StockFlow<small>inventory intelligence</small></span></button><button id="collapse" title="Collapse sidebar">‹</button></div><div class="side-search"><span>⌕</span><input id="globalSearch" placeholder="Search SKU or product…"></div><nav>${pages.map((p,i)=>`<button title="${p}" class="${p===state.page?'active':''}" data-page="${p}"><i>${icons[i]}</i><span>${p}</span></button>`).join('')}</nav><div class="side-bottom"><button id="sync" class="sync-side" title="Sync Google Sheets">↻ <span>Sync Sheets</span></button><div class="source ${state.live?'live':'cached'}"><i></i><span>${state.live?'LIVE / SYNCED':'CACHED / NOT CONNECTED'}</span></div></div></aside><main><header><div><span class="eyebrow">${state.page}</span><h1>${state.page==='Dashboard'?'Inventory control center':state.page}</h1></div><span class="muted">${state.meta.stock?.rows||0} stock rows · ${state.meta.sales?.rows||0} sales rows</span></header><section id="content"></section></main></div></div>`}
function cards(items){return `<div class="cards">${items.map(([l,v,n])=>`<article><small>${l}</small><strong>${v}</strong>${n?`<em>${n}</em>`:''}</article>`).join('')}</div>`}
function table(rows,columns,{detail=false}={}){const page=Math.max(1,state.tablePage||1),size=50,pages=Math.max(1,Math.ceil(rows.length/size)),shown=rows.slice((page-1)*size,page*size);return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th data-col="${esc(c)}"><button class="sort" data-sort="${esc(c)}">${esc(c)} ↕</button></th>`).join('')}</tr></thead><tbody>${shown.map(r=>`<tr ${detail?`data-sku="${esc(r['Uniware SKU'])}"`:''}>${columns.map(c=>{let v=r[c],safe=false;if(c==='IMAGE'){const image=String(v||'').trim();v=`<img class="thumb" loading="lazy" src="${image?esc(image):'./public-placeholder.svg'}" alt="${image?'Product image':'No image available'}" onerror="this.src='./public-placeholder.svg'">`;safe=true}if(c==='STOCK')v=fmt(r._stock??num(v));if(c==='Sales 30D')v=fmt(r._m?.d30||0);if(c==='Sales 7D')v=fmt(r._m?.d7||0);if(c==='Sales 90D')v=fmt(r._m?.d90||0);if(c==='Sales 6M')v=fmt(r._m?.d6||0);if(c==='Avg Daily')v=r._m?.avgDaily?fmt(r._m.avgDaily,2):'No Current Sales';if(c==='Days of Stock')v=r._days===null?'No Current Sales':fmt(r._days,1);return `<td data-col="${esc(c)}">${safe?v:esc(v??'')}</td>`}).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}" class="empty">No records to display. Connect and sync Google Sheets in Settings.</td></tr>`}</tbody></table></div>${rows.length>size?`<div class="pager"><button data-prev ${page===1?'disabled':''}>Previous</button><span>Page ${page} of ${pages} · ${rows.length} rows</span><button data-next ${page===pages?'disabled':''}>Next</button></div>`:''}`}
function dashboard(){const inv=inventory(), q=dataQuality(state.sales,state.stock), m=metrics(), totalSales=[...m.values()].reduce((a,x)=>a+x.total,0), sum=k=>[...m.values()].reduce((a,x)=>a+x[k],0),zero=inv.filter(x=>x._stock===0).length,low=inv.filter(x=>x._stock>0&&x._stock<=10).length;return `<div class="sheet-banner"><b>▣ GOOGLE SHEETS</b><span>${state.config.stock?.tab||'No Stock Sheet selected'}</span><em>${state.meta.stock?.rows||0} SKUs loaded</em><button data-page="Settings">Manage connection</button></div>`+cards([['Total items',fmt(state.stock.length),`${fmt(inv.reduce((a,x)=>a+(x._stock||0),0))} units on hand`],['Low stock alerts',fmt(low+zero),`${zero} zero stock · ${low} low (≤10)`],['Today’s edits','—','Audit-safe stock adjustments'],['Last sync',state.meta.stock?.at||'Never',state.live?'Live connection':'Cached data']])+`<div class="split"><section class="panel"><h2>Main inventory table</h2><p>Live source values with derived sales context.</p>${table(inv.slice(0,8),['IMAGE','Uniware SKU','Item','Color','Size','MRP','STOCK','Sales 30D','Days of Stock'],{detail:true})}</section><section class="panel audit"><h2>Live sheet log</h2><div id="auditFeed">Loading latest updates…</div></section></div>`}
function inventoryPage(){let data=inventory();return `<div class="toolbar"><input id="search" placeholder="Search SKU, item or product…"><details><summary>Columns</summary>${['IMAGE','Simplified','Item','Color','Size','EAN','ASIN','MRP'].map(x=>`<label><input class="col" type="checkbox" data-col="${x}" checked> ${x}</label>`).join('')}</details><button id="importCsv">Import CSV</button><button id="export">Export CSV</button><span>${data.length} stock rows</span></div><input id="csvFile" type="file" accept=".csv,text/csv" hidden>${table(data,['IMAGE','Uniware SKU','Simplified','Item','Color','Size','STOCK','EAN','ASIN','MRP','Sales 7D','Sales 30D','Sales 90D','Sales 6M','Avg Daily','Days of Stock'],{detail:true})}`}
function salesPage(){const portals=[...new Set(state.sales.map(x=>x.Portal).filter(Boolean))];return `<div class="toolbar filters"><input id="search" placeholder="Search sales…"><input id="skuFilter" placeholder="SKU filter"><input id="fromDate" type="date"><input id="toDate" type="date"><select id="portal"><option value="">All portals</option>${portals.map(x=>`<option>${esc(x)}</option>`).join('')}</select><button id="export">Export CSV</button></div>${table(state.sales,SALES_COLUMNS)}`}
function replenish(){const d=inventory().filter(x=>x._m?.avgDaily>0).sort((a,b)=>a._days-b._days);return `<div class="notice">Reorder quantity cannot currently be calculated from the available data. This view uses source STOCK and sales velocity only.</div><div class="toolbar"><input id="search" placeholder="Search replenishment…"><input id="coverageFilter" type="number" min="0" placeholder="Max days of stock"><span>${d.length} SKUs with current sales</span></div>${table(d,['IMAGE','Uniware SKU','Simplified','Item','Color','Size','STOCK','Sales 7D','Sales 30D','Sales 90D','Sales 6M','Avg Daily','Days of Stock'])}`}
function quality(){const q=dataQuality(state.sales,state.stock), dup=suspiciousDuplicates(state.sales);return cards([['Unmatched sales SKU',q.unmatched.length],['Duplicate stock SKU',q.duplicates.length],['Missing stock SKU',q.missingStockSku],['Invalid Qty',q.invalidQty],['Invalid / Missing Date',q.invalidDate],['Suspicious repeated sales',dup.length]])+`<div class="split"><section class="panel"><h2>Unmatched sales</h2>${table(q.unmatched,['Date','Sku','Qty','Portal'])}</section><section class="panel"><h2>Duplicate stock SKUs</h2>${q.duplicates.length?`<ul>${q.duplicates.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>No duplicate SKUs found.</p>'}</section></div>`}
function analytics(){const m=metrics(), top=[...m].map(([sku,x])=>({'SKU':sku,'Total Qty':x.total,'Sales 30D':x.d30,'Sales 6M':x.d6,'Latest Sale':date(x.latest)})).sort((a,b)=>b['Total Qty']-a['Total Qty']);const dim=state.analyticsDim, grouped={};state.sales.forEach(r=>{const k=r[dim]||'(Missing)';grouped[k]=(grouped[k]||0)+(num(r.Qty)||0)});const dims=['Portal','Month','Colour','Size','Simplified','Quality'];return `<div class="split"><section class="panel"><h2>Sales by SKU</h2>${table(top,['SKU','Total Qty','Sales 30D','Sales 6M','Latest Sale'])}</section><section class="panel"><h2>Sales by attribute</h2><select id="analyticsDim">${dims.map(x=>`<option ${x===dim?'selected':''}>${x}</option>`).join('')}</select>${table(Object.entries(grouped).map(([Attribute,Qty])=>({Attribute,Qty})).sort((a,b)=>b.Qty-a.Qty),['Attribute','Qty'])}</section></div>`}
function settings(){const c=state.config;return `<div class="settings"><div class="notice">Google Sheets is the source of truth. Cached data is labelled and is only used for resilience.</div><section class="panel"><h2>Google authentication</h2><p>Authentication and Sheets access are handled server-side. The browser never receives OAuth credentials or access tokens.</p><button id="auth" class="primary">Sign in with Google</button><span id="authstate"></span></section>${['sales','stock'].map(k=>`<section class="panel"><h2>${k==='sales'?'Sales':'Stock'} Google Sheet</h2><button class="picker" data-picker="${k}">Choose from Google Drive</button><label>Spreadsheet URL or ID<input id="${k}Url" value="${esc(c[k].url)}" placeholder="Choose a sheet or paste a URL"></label><label>Worksheet / tab<input id="${k}Tab" value="${esc(c[k].tab)}" placeholder="Choose a worksheet"></label><button data-save="${k}">Save connection</button><button class="primary" data-sync="${k}">Sync ${k}</button><p class="muted">Last sync: ${state.meta[k]?.at||'Never'} · ${state.meta[k]?.rows||0} rows · Data range: ${state.meta[k]?.range||'Not available'} · ${state.meta[k]?.status||'Not connected'}</p></section>`).join('')}<dialog id="pickerDialog"><div id="pickerContent"></div></dialog></div>`}
function render(){app.innerHTML=header();const c=$('#content');c.innerHTML=state.page==='Dashboard'?dashboard():state.page==='Inventory'?inventoryPage():state.page==='Sales'?salesPage():state.page==='Replenishment'?replenish():state.page==='Data Quality'?quality():state.page==='Analytics'?analytics():settings();bind()}
async function persist(){await save({sales:state.sales,stock:state.stock,config:state.config,meta:state.meta})}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});$('#sync').onclick=()=>syncAll();
 const collapse=$('#collapse'),brandToggle=$('#brandToggle'),sidebar=$('aside');if(collapse)collapse.onclick=()=>toggleSidebar(true);if(brandToggle)brandToggle.onclick=()=>{if(state.sidebarCollapsed)toggleSidebar(false)};function toggleSidebar(collapsed){state.sidebarCollapsed=collapsed;sidebar.classList.toggle('collapsed',collapsed);setTimeout(()=>window.dispatchEvent(new Event('resize')),260)}
 const global=$('#globalSearch');if(global)global.onkeydown=e=>{if(e.key==='Enter'){state.page='Inventory';render();setTimeout(()=>{const local=$('#search');if(local){local.value=global.value;local.dispatchEvent(new Event('input'))}},0)}};
 const search=$('#search');const applySalesFilters=()=>{const term=(search?.value||'').toLowerCase(),sku=($('#skuFilter')?.value||'').toLowerCase(),portal=$('#portal')?.value||'',from=$('#fromDate')?.value,to=$('#toDate')?.value,coverage=Number($('#coverageFilter')?.value||0);document.querySelectorAll('tbody tr').forEach((r,i)=>{const x=state.sales[i],d=x&&parseDate(x.Date);r.hidden=state.page==='Sales'?!x||(!r.textContent.toLowerCase().includes(term))||(!normalizeSku(x.Sku).toLowerCase().includes(sku))||(portal&&x.Portal!==portal)||(from&&(!d||d<new Date(from)))||(to&&(!d||d>new Date(`${to}T23:59:59`))):state.page==='Replenishment'?(coverage&&Number(r.cells[r.cells.length-1]?.textContent)>coverage)||!r.textContent.toLowerCase().includes(term):!r.textContent.toLowerCase().includes(term)})};if(search)search.oninput=applySalesFilters;['#skuFilter','#portal','#fromDate','#toDate','#coverageFilter'].forEach(id=>{const e=$(id);if(e)e.oninput=e.onchange=applySalesFilters});
 const exp=$('#export');if(exp)exp.onclick=()=>exportCsv(state.page==='Sales'?state.sales:inventory(),state.page==='Sales'?SALES_COLUMNS:STOCK_COLUMNS,'stockflow-export.csv');
 const importCsv=$('#importCsv'),csvFile=$('#csvFile');if(importCsv&&csvFile){importCsv.onclick=()=>csvFile.click();csvFile.onchange=async()=>{const file=csvFile.files?.[0];if(!file)return;const text=await file.text(),headers=text.split(/\r?\n/)[0].split(',').map(x=>x.trim().replace(/^"|"$/g,'')),missing=STOCK_COLUMNS.filter(x=>!headers.includes(x));if(missing.length)return alert(`This CSV cannot be imported because it is missing: ${missing.join(', ')}.`);alert(`Validated ${file.name}. To protect Google Sheets as the source of truth, CSV data is not applied locally. Import the file into the connected Stock Google Sheet, then choose Sync Sheets.`)}}
 document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const k=b.dataset.save;state.config[k]={url:$(`#${k}Url`).value.trim(),tab:$(`#${k}Tab`).value.trim()};await persist();alert('Connection saved locally.')});document.querySelectorAll('[data-sync]').forEach(b=>b.onclick=()=>sync(b.dataset.sync));const auth=$('#auth');if(auth)auth.onclick=authorize;
 document.querySelectorAll('.picker').forEach(b=>b.onclick=()=>openPicker(b.dataset.picker));document.querySelectorAll('.sort').forEach(b=>b.onclick=()=>{const th=b.closest('th'),index=[...th.parentElement.children].indexOf(th),body=th.closest('table').tBodies[0],rows=[...body.rows].sort((a,z)=>a.cells[index].textContent.localeCompare(z.cells[index].textContent,undefined,{numeric:true}));if(b.dataset.dir!=='desc'){rows.reverse();b.dataset.dir='desc'}else b.dataset.dir='asc';rows.forEach(r=>body.append(r))});document.querySelectorAll('[data-prev]').forEach(b=>b.onclick=()=>{state.tablePage--;render()});document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{state.tablePage++;render()});document.querySelectorAll('.col').forEach(b=>b.onchange=()=>document.querySelectorAll(`[data-col="${b.dataset.col}"]`).forEach(x=>x.hidden=!b.checked));document.querySelectorAll('tr[data-sku]').forEach(r=>r.onclick=()=>openDetail(r.dataset.sku));const dim=$('#analyticsDim');if(dim)dim.onchange=()=>{state.analyticsDim=dim.value;render()};fetch('/api/auth/status').then(r=>r.json()).then(r=>{csrf=r.csrf||csrf;const x=$('#authstate');if(x)x.textContent=r.authorized?' Connected':' Not connected'}).catch(()=>{});
 const auditFeed=$('#auditFeed');if(auditFeed)fetch('/api/audit').then(r=>r.json()).then(x=>auditFeed.innerHTML=(x.entries||[]).slice(0,6).map(e=>`<div class="audit-entry"><b>${esc(e.sku)}</b><span>${fmt(e.previous)} → ${fmt(e.next)} (${e.delta>0?'+':''}${fmt(e.delta)})</span><small>${esc(e.reason)} · ${date(new Date(e.at))}</small></div>`).join('')||'<p>No stock changes have been logged yet.</p>').catch(()=>auditFeed.textContent='Audit history unavailable.');}
async function openPicker(kind){const dialog=$('#pickerDialog'),out=$('#pickerContent');try{out.innerHTML='<h2>Choose a Google Sheet</h2><p>Loading your spreadsheets…</p>';dialog.showModal();const r=await fetch('/api/files'),x=await r.json();if(!r.ok)throw Error(x.error);out.innerHTML=`<h2>Choose a Google Sheet</h2><input id="pickSearch" placeholder="Search files…">${(x.files||[]).map(f=>`<button class="file" data-id="${f.id}" data-name="${esc(f.name)}">${esc(f.name)}<small>${f.modifiedTime?new Date(f.modifiedTime).toLocaleDateString():''}</small></button>`).join('')||'<p>No Google Sheets found.</p>'}<button id="closePicker">Cancel</button>`;$('#closePicker').onclick=()=>dialog.close();$('#pickSearch').oninput=e=>document.querySelectorAll('.file').forEach(b=>b.hidden=!b.dataset.name.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelectorAll('.file').forEach(b=>b.onclick=()=>pickTabs(kind,b.dataset.id,b.dataset.name))}catch(e){out.innerHTML=`<h2>Could not open picker</h2><p>${esc(e.message)}</p><button id="closePicker">Close</button>`;$('#closePicker').onclick=()=>dialog.close()}}
async function pickTabs(kind,id,name){const out=$('#pickerContent');try{out.innerHTML='<h2>Choose a worksheet</h2><p>Loading tabs…</p>';const r=await fetch(`/api/tabs?id=${encodeURIComponent(id)}`),x=await r.json();if(!r.ok)throw Error(x.error);out.innerHTML=`<h2>${esc(name)}</h2><p>Select the worksheet to use for ${kind} data.</p>${x.tabs.map(tab=>`<button class="file tab" data-tab="${esc(tab)}">${esc(tab)}</button>`).join('')}<button id="closePicker">Cancel</button>`;$('#closePicker').onclick=()=>$('#pickerDialog').close();document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{state.config[kind]={url:id,tab:b.dataset.tab};await persist();$('#pickerDialog').close();render()})}catch(e){out.innerHTML=`<p>${esc(e.message)}</p><button id="closePicker">Close</button>`;$('#closePicker').onclick=()=>$('#pickerDialog').close()}}
function openDetail(sku){const row=inventory().find(x=>normalizeSku(x['Uniware SKU'])===normalizeSku(sku));if(!row)return;const sales=state.sales.filter(x=>normalizeSku(x.Sku)===normalizeSku(sku));const m=row._m||{};const d=document.createElement('dialog');d.className='detail';d.innerHTML=`<button class="close">×</button><h2>${esc(row['Uniware SKU'])}</h2><p>${esc(row.Item||row.Simplified||'No product description')}</p>${row.IMAGE?`<img class="hero" src="${esc(row.IMAGE)}" alt="Product image">`:''}${cards([['STOCK',fmt(row._stock)],['Total Qty Sold',fmt(m.total||0)],['7D Qty',fmt(m.d7||0)],['30D Qty',fmt(m.d30||0)],['90D Qty',fmt(m.d90||0)],['6M Qty',fmt(m.d6||0)],['Average Daily',m.avgDaily?fmt(m.avgDaily,2):'No Sales History'],['Days of Stock',row._days===null?'No Current Sales':fmt(row._days,1)]])}<button id="adjustStock" class="primary">Adjust source STOCK</button><p class="muted">This writes an explicit adjustment to the Stock Sheet and is guarded against stale data. Sales sync never deducts stock.</p><h3>Associated sales records</h3>${table(sales,SALES_COLUMNS)}</dialog>`;document.body.append(d);d.showModal();d.querySelector('.close').onclick=()=>d.remove();d.querySelector('#adjustStock').onclick=async()=>{const delta=Number(prompt('Adjustment quantity: use positive to add, negative to remove.','0'));if(!Number.isFinite(delta)||!delta)return;const reason=prompt('Reason for this adjustment:','Manual adjustment')||'Manual adjustment',id=extract(state.config.stock.url),actionId=crypto.randomUUID();const r=await fetch('/api/stock/adjust',{method:'POST',headers:{'Content-Type':'application/json','X-StockFlow-CSRF':csrf},body:JSON.stringify({id,tab:state.config.stock.tab,sku,expectedStock:row._stock,delta,reason,actionId})}),x=await r.json();if(!r.ok)return alert(x.error||'Adjustment failed.');alert('Stock updated in Google Sheets. Sync Stock to refresh.');d.remove()}}
async function authorize(){window.location.assign('/api/auth/start')}
async function sync(kind){try{const conf=state.config[kind],id=extract(conf.url);if(!id)throw Error('Enter a valid Google Sheet URL or spreadsheet ID.');if(!conf.tab)throw Error('Enter the worksheet/tab name.');const res=await fetch(`/api/sheets?id=${encodeURIComponent(id)}&tab=${encodeURIComponent(conf.tab)}`);const payload=await res.json();if(!res.ok)throw Error(payload.error||'Google Sheets sync failed.');const rows=rowsToObjects(payload.values||[],kind==='sales'?SALES_COLUMNS:STOCK_COLUMNS),dates=kind==='sales'?rows.map(x=>parseDate(x.Date)).filter(Boolean).sort((a,b)=>a-b):[];state[kind]=rows;state.live=true;state.meta[kind]={at:new Date().toLocaleString(),rows:rows.length,range:dates.length?`${date(dates[0])} – ${date(dates.at(-1))}`:'Not date-based',status:'Live / Synced'};await persist();render()}catch(e){state.live=false;state.meta[kind]={...(state.meta[kind]||{}),status:`Failed: ${e.message}`};await persist();render();alert(e.message)}}
async function syncAll(){await sync('sales');await sync('stock')}
const cached=await load();state={...state,...cached,config:{...state.config,...cached.config,sales:{...state.config.sales,...cached.config?.sales},stock:{...state.config.stock,...cached.config?.stock}}};render();
